name: Genereer concert HTML en publiceer

on:
  schedule:
    - cron: '0 8 * * 0'  # Zondag 10:00 NL tijd (8:00 UTC)
  workflow_dispatch:      # Voor handmatig starten

permissions:
  contents: write         # Nodig om naar gh-pages te kunnen pushen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: python generate_html.py

      - name: Create .nojekyll file (optional)
        run: touch .nojekyll

      - name: Copy HTML to root for GitHub Pages
        run: |
          mkdir public
          mv concerten_g_
