name: Send Weekly Concert Mail

on:
  schedule:
    - cron: '0 9 * * 1'  # Maandag 09:00 UTC
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run mail script
        env:
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  MAIL_TO: ${{ secrets.MAIL_TO }}
        run: python main.py
